### ISSUE TITLE
not working with rails 5.2

### ISSUE THREAD

**Issue by kritik** [godaddy/activerecord-delay_touching#15]
in the code ```@changed_attributes.except!(*changes.keys)``` rails is not filling @changed_attributes any more

**Comment by mtuckergd** [comment]
I'm actually seeing failing tests in any 5.x ActiveRecord version. Will need to dig in further to see what's up.

**Comment by mtuckergh** [comment]
Rails 5.x will not be supported by this library. Please see https://github.com/godaddy/activerecord-delay_touching/issues/13#issuecomment-285949342.

**Comment by Kenneth-KT** [comment]
@kritik A pull request has been created to support Rails 5 with Rails 4 backward compatibility: https://github.com/godaddy/activerecord-delay_touching/pull/21
I have also published a new gem call `activerecord5_delay_touching ` to [rubygems.org](https://rubygems.org/gems/activerecord5_delay_touching), feel free to it until the maintainer publish my change.

**Edit**: Due to some issue, I have yanked the `activerecord5-delay_touching` gem that I published and published another gem called `activerecord5_delay_touching`.
